name: rlasso-site-ci-dev
on:
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:
jobs:
  
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Git Check Out
        uses: actions/checkout@v2
      - name: Node Install
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          check-latest: true
      - name: Get Version
        run: chmod +x scripts/get-version.sh && scripts/get-version.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Install
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DR_TOKEN }}
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: dev-${{env.IMAGE_TAG}}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DR_TOKEN }}
      - name: Docker Push
        run: chmod +x scripts/docker-push.sh && scripts/docker-push.sh dev-${{env.IMAGE_TAG}} ${{github.repository_owner}}